plugins {
    id 'java'
}

group = 'com.gotospawn'
version = '1.2.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.3.build.+'
}

processResources {
    expand version: project.version
}
